[package]
name = "jdw-keyboard-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.4.2"
jdw-osc-lib = { git = "https://github.com/estrandv/jdw-osc-lib.git", branch = "master" }
rosc = "0.10.1"
